/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vigenere;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class vigeneree extends javax.swing.JFrame {


    /**
     * Creates new form vigeneree
     */
    public vigeneree() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        message = new javax.swing.JTextField();
        cle = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        resultat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 3));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 480, 60));
        jPanel1.add(cle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 480, 60));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Crypter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 90, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("Decrypter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, 40));
        jPanel1.add(resultat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 490, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Message");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Clé");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 40, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Resultat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vigenere/bs.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

 if(message.getText().equals("")) {
    JOptionPane.showMessageDialog(null,"Il faut remplir le message à chiffrer","",JOptionPane.WARNING_MESSAGE);
    
}else{
        if(cle.getText().equals("")) {
    JOptionPane.showMessageDialog(null,"Il faut remplir le clé","",JOptionPane.WARNING_MESSAGE);
    
}else {
             if (message.getText().length()!=cle.getText().length()){
     JOptionPane.showMessageDialog(null,"Pour une  meilleur chiffrement, si mieu que la taille de votre clé doit = "+message.getText().length()+" la taile de votre message","",JOptionPane.INFORMATION_MESSAGE);
     
             }
             String plain_text=message.getText();
      String k=cle.getText();
         vigner v=new vigner(plain_text,k);    
     resultat.setText(v.crypt());
    
    
         int confirm= JOptionPane.showConfirmDialog(null,"Est-que tu veut sauvgarder ce text clair dans A.txt et leur crypté dans  B.txt ","sauvgarde",JOptionPane.YES_NO_OPTION);
        if(confirm==0){
             // j'utilise C.txt juste pour reutiliser avec fonction read 
            v.write("C.txt",message.getText());
        v.write("A.txt",v.read("C.txt"));
        v.write("B.txt",resultat.getText());
     
        }}}
        
         

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

if(message.getText().equals("")) {
    JOptionPane.showMessageDialog(null,"Il faut remplir le message à déchiffrer","",JOptionPane.WARNING_MESSAGE);
    
}else{
        if(cle.getText().equals("")) {
    JOptionPane.showMessageDialog(null,"Il faut remplir le clé","",JOptionPane.WARNING_MESSAGE);
    
}else {
           
             String cipher_text=message.getText();
      String k=cle.getText();
         vigner v=new vigner(cipher_text,k);    
     resultat.setText(v.decrypt());
    
       
         int confirm= JOptionPane.showConfirmDialog(null,"Est-que tu veut sauvgarder ce text chiffré dans B.txt et leur décrypté dans A.txt ","sauvgarde",JOptionPane.YES_NO_OPTION);
        if(confirm==0){ 
     // j'utilise c.txt juste pour reutiliser avec fonction read 
            v.write("C.txt",message.getText());
        v.write("B.txt",v.read("C.txt"));
        v.write("A.txt",resultat.getText());
     
     
        }}}
     
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vigeneree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vigeneree().setVisible(true);
            }
        });
   
         
    }
    
    public class vigner{
         public  char letters[]={'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'};
         public  char lettersM[]={'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'};
  public    char msg[];
  public    char cl[];
   public    int clposition[];
   String espace=" ";
   String folder = System.getProperty("user.home");
   public  String absolutePath;
    String File_Name ;
   String line="";
    public vigner(String m,String k){
        
   msg=new char[m.length()];
        cl=new char[m.length()];
        clposition=new int[m.length()];
        //msg tableau pour sauvgarder les lettres de  message et cl lettres de cle et aussi pour rendre la taille de  cle comme celle de  message et clposition pour les positions de  chaque lettre de cle 
     if (m.length()==k.length()){
         for (int i = 0; i < m.length(); i++) {
             msg[i]=m.charAt(i);
             cl[i]=k.charAt(i);
         }
     }else{
         int j=k.length();
         int n=0;
         for (int i = 0; i < m.length(); i++) {
             
       msg[i]=m.charAt(i);
       if(msg[i]==espace.charAt(0)){
           cl[i]=espace.charAt(0);
           n++;
       }else{
       cl[i]=k.charAt((i-n)% j);
       }}}
      
      for (int i = 0; i < m.length(); i++) {
      for (int position = 0; position< letters.length;position++){ 
                  if ((cl[i]==letters[position])||(cl[i]==lettersM[position])) {
       clposition[i]=position;
       
      }
      
      
      }
          
      
     }
      
   }
    public String crypt(){
         
     String text_chiffre="";
            for (int i=0;i<msg.length;i++ ){
                int ok=0;
              for (int position = 0; position< letters.length;position++){ 
                  if (msg[i]==letters[position]) {
                   ok=1;
                    int newposition=(position+clposition[i])% 26;
                
                text_chiffre=text_chiffre+letters[newposition];
                  }}
               if(ok==0){
              for (int position = 0; position< lettersM.length;position++) {
                  if (msg[i]==lettersM[position]) {
                   ok=1;
                    int newposition =(position+clposition[i])% 26;
                    text_chiffre=text_chiffre+lettersM[newposition];
                  }}
              }
                if (ok==0){
             
             if(msg[i]==espace.charAt(0)){
                
             text_chiffre=text_chiffre+espace;
             }else{
         text_chiffre=text_chiffre+msg[i];
         }}
              
              
                
              
            }
          
            
            
    return text_chiffre;
    }
    
    
    
    public String decrypt(){
        String text_dechiffre="";
            for (int i=0;i<msg.length;i++ ){
                int ok=0;
              for (int position = 0; position< letters.length;position++){ 
                  if (msg[i]==letters[position]) {
                   ok=1;
                    int newposition=(position-clposition[i])% 26;
                    if(newposition<0){
                      newposition=newposition+26;  
                    }
                
                text_dechiffre=text_dechiffre+letters[newposition];
                  }}
               if(ok==0){
              for (int position = 0; position< lettersM.length;position++) {
                  if (msg[i]==lettersM[position]) {
                   ok=1;
                    int newposition =(position-clposition[i])% 26;
                    if(newposition<0){
                      newposition=newposition+26;  
                    }
                    text_dechiffre=text_dechiffre+lettersM[newposition];
                  }}
              }
                if (ok==0){
             
             if(msg[i]==espace.charAt(0)){
                
             text_dechiffre=text_dechiffre+espace;
             }else{
         text_dechiffre=text_dechiffre+msg[i];
         }}
              
              
              
              
            }
            
            
            
    return text_dechiffre;
    }
    
    
      public  void write(String File_Name,String content) {
        absolutePath = folder + File.separator +File_Name;
    try(BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(absolutePath))) {
    String fileContent = content;
    bufferedWriter.write(fileContent);
    
} catch (IOException e) {
    // Exception handling
}
    }
     
      // lire le contenue d'un fichier
       public  String read(String File_Name) {
        absolutePath = folder + File.separator +File_Name;
      String content="";
    try(BufferedReader bufferedReader = new BufferedReader(new FileReader(absolutePath))) {
    line = bufferedReader.readLine();
   
    while(line != null) {
       
         content=line;
        line = bufferedReader.readLine();
        
    }
    
} catch (FileNotFoundException e) {
    // Exception handling
} catch (IOException e) {
    // Exception handling
}
        return content;
    }
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField cle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField message;
    public javax.swing.JTextField resultat;
    // End of variables declaration//GEN-END:variables
}
